---
swagger: "2.0"
info:
  description: >-
    This is a simple sample server Petstore server.
  version: "1.0.0"
  title: "Swagger Petstore"
  contact:
    email: "apiteam@swagger.io"
host: "petstore.swagger.io"
basePath: "/v2"
schemes:
- "https"
- "http"
paths:
  /store/inventory:
    get:
      tags:
      - "store"
      summary: "Returns pet inventories by status"
      description: "Returns a map of status codes to quantities"
      operationId: "getInventory"
      produces:
      - "application/json"
      parameters:
      - $ref: "#/parameters/page"
      responses:
        200:
          description: "successful operation"
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: "#/definitions/Category"
            
      security:
      - apikey: []

securityDefinitions:
  apikey:
    type: "apiKey"
    name: "apikey"
    in: "query"

definitions:
  Category:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        
parameters:
  page:
    name: page
    in: query
    type: string
    description: page to request
